version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=file:./prod.db
      - NODE_ENV=production
      - PORT=8000
    volumes:
      - ./data:/app/data
    restart: unless-stopped